version: "3.8"
services:
  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: nestjs_skeleton
      JWT_SECRET: changeme
      JWT_EXPIRES_IN: 3600s
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: