name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: nestjs_skeleton_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: nestjs_skeleton_test
      JWT_SECRET: testsecret
      JWT_EXPIRES_IN: 3600s

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Wait for Postgres
        run: |
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Run migrations
        run: npm run typeorm migration:run

      - name: Run tests
        run: npm test

      - name: Lint
        run: npm run lint || true